# Generated by Django 3.1.4 on 2020-12-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lab',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(help_text='Brief description of the lab.')),
                ('lab_url', models.CharField(help_text='The url of the repository where I uploaded my solution.', max_length=200)),
            ],
        ),
    ]
